#!/usr/bin/env bash

SOURCE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

BUILDFOLDER="$SOURCE/../../rbfxbuild"
RBFXFOLDER="$SOURCE/../../rbfx"

mkdir $BUILDFOLDER

cmake -G Xcode -T buildsystem=1 -DCMAKE_TOOLCHAIN_FILE=$RBFXFOLDER/CMake/Toolchains/IOS.cmake -DENABLE_BITCODE=OFF -DPLATFORM=OS64COMBINED -DDEPLOYMENT_TARGET=11 -DURHO3D_GRAPHICS_API=GLES3 -DBUILD_SHARED_LIBS=ON -DURHO3D_GLOW=ON -DURHO3D_FEATURES="CSHARP;SYSTEMUI" -DURHO3D_NETFX=netstandard2.0 -DURHO3D_PROFILING=OFF -DURHO3D_PLAYER=OFF -DURHO3D_EXTRAS=OFF -DURHO3D_TOOLS=OFF -DURHO3D_RMLUI=ON -DSWIG_MODULE_Urho3D_DLLIMPORT=__Internal -DSWIG_MODULE_ImGui_DLLIMPORT=__Internal -S $RBFXFOLDER -B $BUILDFOLDER
