# Build project for Mac

jobs:
- job: Build_Mac
  displayName: 'Build Mac'
  timeoutInMinutes: 90
  pool:
    vmImage: 'macOS-latest'
  variables:
    rbfxFolder: $(Build.SourcesDirectory)/rbfx
    buildFolder: $(Build.SourcesDirectory)/rbfxbuild
    nugetFolder: $(Build.ArtifactStagingDirectory)/nuget

  steps:
  - checkout: self
    submodules: true
    displayName: 'Checkout project'

  - template: Add-ToolsToPath.yaml

  - bash: |
      brew install ccache
    displayName: 'Install CCache'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'

  - template: Fetch-CCache.yaml

  - template: Build-rbfx.yaml
    parameters:
      cmakeExtraArgs: -DCMAKE_CXX_COMPILER_LAUNCHER=$(EM_COMPILER_WRAPPER) -DCMAKE_C_COMPILER_LAUNCHER=$(EM_COMPILER_WRAPPER)
      buildDotNet: false
      buildEditor: false

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(buildFolder)/bin'
      contents: 'libUrho3D.dylib' 
      targetFolder: '$(nugetFolder)/native/osx'
      overWrite: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish game binaries'
    inputs:
      targetPath: '$(nugetFolder)'
      artifactName: 'osx-nuget'

