# Build project for Mac

jobs:
- job: Build_Mac
  displayName: 'Build Mac'
  timeoutInMinutes: 90
  pool:
    vmImage: 'macOS-latest'
  variables:
    rbfxFolder: $(Agent.BuildDirectory)/s/rbfx
    buildFolder: $(Agent.BuildDirectory)/s/rbfxbuild
    nugetFolder: $(Build.ArtifactStagingDirectory)/nuget
    CCACHE_DIR: $(Agent.BuildDirectory)/__ccache

  steps:
  - checkout: self
    submodules: true
    displayName: 'Checkout project'

  - template: Add-ToolsToPath.yaml

  - bash: |
      brew install ccache
    displayName: 'Install CCache'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'

  - template: Fetch-CCache.yaml

  - template: Build-rbfx.yaml
    parameters:
      cmakeExtraArgs: -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
      buildDotNet: false

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(buildFolder)/bin'
      contents: 'libUrho3D.dylib' 
      targetFolder: '$(nugetFolder)/native/osx'
      overWrite: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish game binaries'
    inputs:
      targetPath: '$(nugetFolder)'
      artifactName: 'osx-nuget'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish swig'
    inputs:
      targetPath: '$(buildFolder)/bin/swig'
      artifactName: 'mac-swig'
