# Build project for Mac

jobs:
- job: Build_Linux_SDK
  displayName: 'Build Linux SDK'
  timeoutInMinutes: 90
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    rbfxFolder: $(Build.SourcesDirectory)/rbfx
    buildFolder: $(Build.SourcesDirectory)/rbfxbuild
    nugetFolder: $(Build.ArtifactStagingDirectory)/nuget

  steps:
  - checkout: self
    submodules: true
    displayName: 'Checkout project'

  - template: Add-ToolsToPath.yaml

  - template: Install-LinuxLibs.yaml

  - template: Fetch-CCache.yaml
    parameters:
      folder:  'sdk/'
      
  - template: Build-SDK.yaml
    parameters:
      cmakeExtraArgs: -DCMAKE_CXX_COMPILER_LAUNCHER=$(EM_COMPILER_WRAPPER) -DCMAKE_C_COMPILER_LAUNCHER=$(EM_COMPILER_WRAPPER)
      buildDotNet: false

  - bash: strip ./libUrho3D.so
    displayName: 'Strip libUrho3D.so'
    workingDirectory: '$(buildFolder)/bin'
    continueOnError: true 
    failOnStderr: true

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(buildFolder)/bin/'
      contents: '*' 
      targetFolder: '$(nugetFolder)/bin/'
      overWrite: true
      
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(buildFolder)/shared/'
      contents: '*' 
      targetFolder: '$(nugetFolder)/shared/'
      overWrite: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish SDK binaries'
    inputs:
      targetPath: '$(nugetFolder)'
      artifactName: 'linux-sdk'

  - script: |
      dotnet tool run ezpipeline -- zip-to-blob --connection-string "$(CCACHE_BLOB_CONNECTION_STRING)" -i "$(nugetFolder)" -c "sdk" -n "linux.zip" -l Fastest --overwrite
    continueOnError: true 
    displayName: 'Upload binary to container'