# Build project for Mac

jobs:
- job: Build_Mac
  displayName: 'Build Mac'
  pool:
    vmImage: 'macOS-latest'
  variables:
    rbfxFolder: $(Agent.BuildDirectory)/s/rbfx
    buildFolder: $(Agent.BuildDirectory)/s/rbfxbuild
    nugetFolder: $(Build.ArtifactStagingDirectory)/nuget

  steps:
  - checkout: self
    submodules: true
    displayName: 'Checkout project'

  - template: Add-ToolsToPath.yaml

  - template: Build-rbfx.yaml
    parameters:
      buildDotNet: false

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(buildFolder)/bin'
      contents: 'libUrho3D.dylib' 
      targetFolder: '$(nugetFolder)/native/osx'
      overWrite: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish game binaries'
    inputs:
      targetPath: '$(nugetFolder)'
      artifactName: 'osx-nuget'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish swig'
    inputs:
      targetPath: '$(buildFolder)/bin/swig'
      artifactName: 'mac-swig'
