# Build project for Mac

jobs:
- job: Build_Mac_SDK
  displayName: 'Build Mac SDK'
  timeoutInMinutes: 90
  pool:
    vmImage: 'macOS-latest'
  variables:
    rbfxFolder: $(Build.SourcesDirectory)/rbfx
    buildFolder: $(Build.SourcesDirectory)/rbfxbuild
    nugetFolder: $(Build.ArtifactStagingDirectory)/nuget

  steps:
  - checkout: self
    submodules: true
    displayName: 'Checkout project'

  - template: Add-ToolsToPath.yaml

  - bash: |
      brew install ccache
    displayName: 'Install CCache'
    workingDirectory: '$(Build.ArtifactStagingDirectory)'

  - template: Fetch-CCache.yaml
    parameters:
      folder:  'sdk/'

  - template: Build-SDK.yaml
    parameters:
      cmakeExtraArgs: -DCMAKE_CXX_COMPILER_LAUNCHER=$(EM_COMPILER_WRAPPER) -DCMAKE_C_COMPILER_LAUNCHER=$(EM_COMPILER_WRAPPER)
      buildDotNet: false

  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(buildFolder)/../../bin/'
      contents: '*' 
      targetFolder: '$(nugetFolder)'
      overWrite: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish SDK binaries'
    inputs:
      targetPath: '$(nugetFolder)'
      artifactName: 'mac-sdk'

  - script: |
      dotnet tool run ezpipeline -- zip-to-blob --connection-string "$(CCACHE_BLOB_CONNECTION_STRING)" -i "$(nugetFolder)" -c "sdk" -n "mac.zip" -l Fastest --overwrite
    continueOnError: true 
    condition: true
    displayName: 'Upload binary to container'