# Build project for Mac

jobs:
- job: Build_Linux
  displayName: 'Build Linux'
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    rbfxFolder: $(Agent.BuildDirectory)/s/rbfx
    buildFolder: $(Agent.BuildDirectory)/s/rbfxbuild
    nugetFolder: $(Build.ArtifactStagingDirectory)/nuget

  steps:
  - checkout: self
    submodules: true
    displayName: 'Checkout project'

  - template: Add-ToolsToPath.yaml

  - template: Install-LinuxLibs.yaml

  - template: Build-rbfx.yaml
    parameters:
      buildDotNet: false

  - bash: strip ./libUrho3D.so
    displayName: 'Strip libUrho3D.so'
    workingDirectory: '$(buildFolder)/bin'
    failOnStderr: true

  - task: CopyFiles@2
    displayName: 'Copy libUrho3D.so'
    inputs:
      sourceFolder: '$(buildFolder)/bin'
      contents: 'libUrho3D.so' 
      targetFolder: '$(nugetFolder)/native/linux'
      overWrite: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish binaries'
    inputs:
      targetPath: '$(nugetFolder)'
      artifactName: 'linux-nuget'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish swig'
    inputs:
      targetPath: '$(buildFolder)/bin/swig'
      artifactName: 'linux-swig'