# Build project for UWP
parameters:
  platform: 'x64'
  configuration: 'RelWithDebInfo'
  buildDotNet: true

jobs:
- job: Build_UWP_${{ parameters.platform }}
  displayName: 'Build UWP ${{ parameters.platform }}'
  timeoutInMinutes: 120
  pool:
    vmImage: 'windows-latest'
  variables:
    rbfxFolder: $(Build.SourcesDirectory)/rbfx
    buildFolder: $(Build.SourcesDirectory)/rbfxbuild
    nugetFolder: $(Build.ArtifactStagingDirectory)/nuget

  steps:
  - checkout: self
    submodules: true
    displayName: 'Checkout project'

  - template: Add-ToolsToPath.yaml

  - script: dotnet tool run azurepipelinetool winsdkenv --buildPlatform x64
    displayName: 'Setup Windows SDK Environment'

  - script: dotnet tool run azurepipelinetool vsenv --buildPlatform x64
    displayName: 'Setup Visual Studio Environment'

  - template: Fetch-CCache.yaml

  - template: Build-rbfx.yaml
    parameters:
      buildDotNet: ${{ parameters.buildDotNet }}
      cmakeExtraArgs: >-
        -G "Visual Studio 17 2022" -A "${{ parameters.platform }}"
        -DCMAKE_BUILD_TYPE=${{ parameters.configuration }}
        -DCMAKE_CXX_COMPILER="cl"
        -DCMAKE_C_COMPILER="cl"
        -DCMAKE_SYSTEM_NAME=WindowsStore
        -DCMAKE_SYSTEM_VERSION='10.0'
        -DURHO3D_GRAPHICS_API=D3D11
        -DVS_WINDOWS_TARGET_PLATFORM_MIN_VERSION='10.0.10240.0'
        -DSWIG_MODULE_Urho3D_DLLIMPORT=Urho3D
        -DSWIG_MODULE_ImGui_DLLIMPORT=Urho3D
      configuration: ${{ parameters.configuration }}

  - pwsh: |
      Get-ChildItem -Path $(buildFolder) -Filter *.dll -Recurse -Name| ForEach-Object {
          Write-Host $_
      }
    displayName: 'Find all *.dll'

  - pwsh: |
      New-Item -ItemType Directory -Path $(nugetFolder)/native/uap/${{ parameters.platform }}/ -Force
      copy-item $(buildFolder)/bin/${{ parameters.configuration }}/Urho3D.dll $(nugetFolder)/native/uap/${{ parameters.platform }}/Urho3D.dll -Force
      copy-item $(buildFolder)/bin/${{ parameters.configuration }}/Urho3D.pdb $(nugetFolder)/native/uap/${{ parameters.platform }}/Urho3D.pdb -Force
    displayName: 'Copy binary to output'

  - pwsh: |
      New-Item -ItemType Directory -Path $(nugetFolder)/lib/uap10.0 -Force
      copy-item $(buildFolder)/bin/${{ parameters.configuration }}/netstandard2.0/Urho3DNet.dll $(nugetFolder)/lib/uap10.0/Urho3DNet.dll -Force
    displayName: 'Copy .net binary to output'
    condition: and(succeeded(), eq('${{ parameters.buildDotNet }}', true))

  - task: PublishPipelineArtifact@1
    displayName: 'Publish game binaries'
    inputs:
      targetPath: '$(nugetFolder)'
      artifactName: 'win-${{ parameters.platform }}-uap-nuget'
