# Build project for Mac

jobs:
- job: Build_Linux
  displayName: 'Build Linux'
  timeoutInMinutes: 90
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    rbfxFolder: $(Build.SourcesDirectory)/rbfx
    buildFolder: $(Build.SourcesDirectory)/rbfxbuild
    nugetFolder: $(Build.ArtifactStagingDirectory)/nuget

  steps:
  - checkout: self
    submodules: true
    displayName: 'Checkout project'

  - template: Add-ToolsToPath.yaml

  - template: Install-LinuxLibs.yaml

  - template: Fetch-CCache.yaml
      
  - template: Build-rbfx.yaml
    parameters:
      cmakeExtraArgs: -DCMAKE_CXX_COMPILER_LAUNCHER=$(EM_COMPILER_WRAPPER) -DCMAKE_C_COMPILER_LAUNCHER=$(EM_COMPILER_WRAPPER)
      buildDotNet: false

  - bash: strip ./libUrho3D.so
    displayName: 'Strip libUrho3D.so'
    workingDirectory: '$(buildFolder)/bin'
    failOnStderr: true

  - task: CopyFiles@2
    displayName: 'Copy libUrho3D.so'
    inputs:
      sourceFolder: '$(buildFolder)/bin'
      contents: 'libUrho3D.so' 
      targetFolder: '$(nugetFolder)/native/linux'
      overWrite: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish binaries'
    inputs:
      targetPath: '$(nugetFolder)'
      artifactName: 'linux-nuget'
