# Publish nuget package

jobs:
- job: PublishEditor
  displayName: 'Publish Editor Nuget'
  pool:
    vmImage: 'windows-latest'
  variables:
    rbfxFolder: $(Build.SourcesDirectory)/rbfx
    buildFolder: $(Build.SourcesDirectory)/rbfxbuild
    nugetFolder: $(Build.ArtifactStagingDirectory)/nuget

  steps:
  - template: Install-DotNet.yaml
  
  - script: dotnet tool run ezpipeline git-height-version -i '$(Build.SourcesDirectory)/.azurepipelines/version.txt' -b 0.3.7.320 --variable VERSION
    displayName: 'Generate version environment variable'

  - task: NuGetToolInstaller@1
    inputs:
      checkLatest: true

  - template: Fetch-NugetArtifact.yaml
    parameters:
      artifact: 'Windows_NT_EditorNuget'

  - task: NuGetCommand@2
    displayName: 'Publish to local feed'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '$(VstsFeed)'
      allowPackageConflicts: true

  - task: NuGetCommand@2
    displayName: 'Publish to nuget.org'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      publishFeedCredentials: 'rbfx_nuget_org'
      nuGetFeedType: 'external'
      versioningScheme: 'byEnvVar'
      versionEnvVar: 'VERSION'
      allowPackageConflicts: true
