# Build project for Windows
parameters:
  configuration: 'RelWithDebInfo'
  enableCache: true
  debugCache: false

jobs:
- job: SetBuildNumber
  displayName: 'SetBuildNumber'
  pool:
    vmImage: 'windows-latest'

  steps:
  - checkout: self
    displayName: 'Checkout project'

  - template: Install-DotNet.yaml

  - script: dotnet tool run ezpipeline git-height-version -i $(Build.SourcesDirectory)/.azurepipelines/version.txt -b 0.4.0 --variable VERSION
    displayName: 'Generate version environment variable'

  - pwsh: Write-Host "##vso[build.updatebuildnumber]$(VERSION)"
    displayName: 'Update Build Number'
