#Azure DevOps yaml script to build and publish rbfx game on 2 platforms

trigger: none
#- master

stages:
- stage: Editor_Build
  displayName: Windows Editor Build
  jobs:
  - job: Build_Windows
    displayName: 'Windows Editor Build'
    pool:
      vmImage: 'windows-latest'
    variables:
      rbfxFolder: $(Build.SourcesDirectory)/rbfx
      buildFolder: $(Build.SourcesDirectory)/rbfxbuild
      nugetFolder: $(Build.ArtifactStagingDirectory)/nuget

    steps:
    - checkout: self
      submodules: true
      displayName: 'Checkout project'

    - template: Templates/Add-ToolsToPath.yaml

    - template: Templates/Build-Editor.yaml
      parameters:
        cmakeExtraArgs: -G "Visual Studio 17 2022" -A x64 -DURHO3D_GRAPHICS_API=D3D11
        
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Win'
        publishLocation: 'Container'

  - job: Build_Mac
    displayName: 'Mac Editor Build'
    timeoutInMinutes: 90
    pool:
      vmImage: 'macOS-latest'
    variables:
      rbfxFolder: $(Build.SourcesDirectory)/rbfx
      buildFolder: $(Build.SourcesDirectory)/rbfxbuild
      nugetFolder: $(Build.ArtifactStagingDirectory)/nuget

    steps:
    - checkout: self
      submodules: true
      displayName: 'Checkout project'

    - template: Templates/Add-ToolsToPath.yaml

    - template: Templates/Build-Editor.yaml

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'OSX'
        publishLocation: 'Container'

  - job: Build_Linux
    displayName: 'Linux Editor Build'
    timeoutInMinutes: 90
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      rbfxFolder: $(Build.SourcesDirectory)/rbfx
      buildFolder: $(Build.SourcesDirectory)/rbfxbuild
      nugetFolder: $(Build.ArtifactStagingDirectory)/nuget

    steps:
    - checkout: self
      submodules: true
      displayName: 'Checkout project'

    - template: Templates/Add-ToolsToPath.yaml

    - template: Templates/Install-LinuxLibs.yaml

    - template: Templates/Build-Editor.yaml

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Linux'
        publishLocation: 'Container'
