#Azure DevOps yaml script to build and publish rbfx game on 2 platforms

trigger:
- master
# trigger: none

stages:
- stage: Build
  displayName: Build
  jobs:
  - template: Templates/Build-iOS.yaml
  - template: Templates/Build-Win.yaml
  - template: Templates/Build-UWP.yaml
    parameters:
      platform: 'x64'
      buildDotNet: true
  - template: Templates/Build-UWP.yaml
    parameters:
      platform: 'ARM64'
      buildDotNet: false
  - template: Templates/Build-Mac.yaml
  - template: Templates/Build-Linux.yaml
  - template: Templates/Build-Android.yaml

- stage: Publish
  displayName: Publish Nuget
  dependsOn:
    - Build
  jobs:
  - template: Templates/Publish-Nuget.yaml
  